#ifndef ARGUMENTS_H
#define ARGUMENTS_H

// C
#include <stdint.h>

// Deslocamento dos argumentos
#define ARGUMENT_PRINT_PLATFORM_NAME 0
#define ARGUMENT_PRINT_PLATFORM_VENDOR 1
#define ARGUMENT_PRINT_PLATFORM_PROFILE 2
#define ARGUMENT_PRINT_PLATFORM_VERSION 3
#define ARGUMENT_PRINT_PLATFORM_EXTENSIONS 4
#define ARGUMENT_PRINT_PLATFORM_DEVICES 5
#define ARGUMENT_PRINT_DEVICE_NAME 6
#define ARGUMENT_PRINT_DEVICE_VENDOR 7
#define ARGUMENT_PRINT_DEVICE_PROFILE 8
#define ARGUMENT_PRINT_DEVICE_VERSION 9
#define ARGUMENT_PRINT_DEVICE_TYPE 10

void parseArguments(const int argc, char *const argv[]);

uint8_t getArgument(const uint8_t shift);

#endif
