name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Generate
      run: cmake -B build

    - name: Build
      run: cmake --build build
