name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Generate
      working-directory: ${{github.workspace}}
      run: cmake -B build

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build build
