name: Linux

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Clonar dependências
      working-directory: ${{github.workspace}}
      run: |
        git clone https://github.com/KhronosGroup/OpenCL-Headers.git dependencies/OpenCL-Headers
        git clone https://github.com/KhronosGroup/OpenCL-ICD-Loader.git dependencies/OpenCL-ICD-Loader

    - name: Compilar dependências
      working-directory: ${{github.workspace}}
      run: |
        mkdir dependencies/OpenCL-ICD-Loader/build
        cmake -D OPENCL_ICD_LOADER_HEADERS_DIR=dependencies/OpenCL-Headers -S dependencies/OpenCL-ICD-Loader -B dependencies/OpenCL-ICD-Loader/build
        cmake --build dependencies/OpenCL-ICD-Loader/build

    - name: Criar ambiente de compilação
      working-directory: ${{github.workspace}}
      run: |
        mkdir build

    - name: Configurar CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Compilar
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Testar
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
